### ISSUE TITLE
ydb/core/ydb_convert/ydb_convert.cpp:202: Unknown protobuf type

### ISSUE THREAD

**Issue by vladkolotvin** [ydb-platform/ydb-nodejs-sdk#147]
При выполнении следующего кода получил ошибку где-то в недрах ядра YDB.
```
const result = await driver.tableClient.withSession(async (session) => {
        return await withRetries(async () => {
            const query = `DECLARE $phone_number AS Utf8;

                           SELECT COUNT(*) FROM call_password
                           WHERE phone_number = $phone_number AND created_at > CurrentUtcTimestamp() - Interval("PT10M");
                            
                           SELECT COUNT(*) FROM call_password
                           WHERE phone_number = $phone_number AND created_at > CurrentUtcTimestamp() - Interval("PT1H");
                            
                           SELECT COUNT(*) FROM call_password
                           WHERE phone_number = $phone_number AND created_at > CurrentUtcTimestamp() - Interval("P1D");`;

            const preparedQuery = await session.prepareQuery(query);
            return await session.executeQuery(preparedQuery, {
                '$phone_number': ctx.request.query.number
            });
        });
    });
```

Ошибка:
```
Error: BadRequest: [
     {
       "message": "Failed to parse query parameters.",
       "issues": [
         {
           "message": "ydb/core/ydb_convert/ydb_convert.cpp:202: Unknown protobuf type: ",
           "issueCode": 1
         }
       ]
     }
   ]
at Function.checkStatus (/usr/src/app/node_modules/ydb-sdk/build/errors.js:56:27)
at Object.getOperationPayload (/usr/src/app/node_modules/ydb-sdk/build/utils.js:127:27)
at Session.executeQuery (/usr/src/app/node_modules/ydb-sdk/build/table.js:391:37)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Session.descriptor.value (/usr/src/app/node_modules/ydb-sdk/build/utils.js:157:20)
at async file:///usr/src/app/src/phone.js:77:20
at async RetryStrategy.retry (/usr/src/app/node_modules/ydb-sdk/build/retries.js:70:24)
at async withRetries (/usr/src/app/node_modules/ydb-sdk/build/retries.js:126:12)
at async file:///usr/src/app/src/phone.js:64:16
at async SessionPool._withSession (/usr/src/app/node_modules/ydb-sdk/build/table.js:643:32)
```

Есть идеи, где может быть проблема?

**Comment by vladkolotvin** [comment]
Такое изменение помогло:
```
return await session.executeQuery(preparedQuery, {
    '$phone_number': TypedValues.utf8(ctx.request.query.number)
});
```
