### ISSUE TITLE
Ошибка при работе с grpc укладывает приложение

### ISSUE THREAD

**Issue by vladkolotvin** [ydb-platform/ydb-nodejs-sdk#150]
Иногда приложение просто падает с такой ошибкой:
```
/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31
    return Object.assign(new Error(message), status);
                         ^

Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  details: 'Connection dropped',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

```
Где ловить непонятно. GRPC используется только в ydb sdk.

**Comment by gayratv** [comment]
Не факт что это YDB виновато :)
Например мой VPN с grpc не дружит и приходится его постоянно выключать.

Также у меня бывают сетевые сбои у моего провайдера - тоже падает.

**Comment by zeruk** [comment]
@vladkolotvin вышла новая версия ydb-sdk@3.5.0, протестируйте, пожалуйста, что она помогла с вашей проблемой
